### PR TITLE
update to 0.8.2

### PR DESCRIPTION
**Pull request by saada**
- Added new CRDs and examples for image automation
- Move to stable channel

Relevant PRs
https://github.com/operator-framework/community-operators/pull/3126
https://github.com/operator-framework/community-operators/pull/3168

### CODE REVIEW

**Comment by squaremo** [comment]
I have no idea how to review this, there's >300 files changed!

**Comment by saada** [comment]
I just need a stamp. No need to review really

**Comment by squaremo** [comment]
If this is for v0.8.2, why are there files in e.g., `.../0.2.2/` that are changed?

**Comment by saada** [comment]
here you go

**Review by stefanprodan — APPROVED** [review]
LGTM

I think we need to improve the cr examples at some point.

**Pull request merged**
