### PR TITLE
Reenabling flux with its network policies

### PR DESCRIPTION
**Pull request by souleb**
Signed-off-by: Soule BA <bah.soule@gmail.com>

This is supported by openshift since version 4.5 at least.

Note: OpenShift SDN cluster network provider comes with some limitations.  Egress network policies are not supported. Do not use it with the current flux version as it is shipped with egress policies. Use a CNI that support Kubernetes network policy instead.

### CODE REVIEW

**Comment by souleb** [comment]
> OpenShift SDN

The openshift doc says: 
> When using the OpenShift SDN cluster network provider, the following limitations apply regarding network policies:

> - Egress network policy as specified by the egress field is not supported.

> - IPBlock is supported by network policy, but without support for except clauses. If you create a policy with an IPBlock section that includes an except clause, the SDN pods log warnings and the entire IPBlock section of that policy is ignored.

**Comment by stefanprodan** [comment]
> Egress network policy as specified by the egress field is not supported.

So does this means Flux will fail to install or the policies are just ignored?

**Comment by souleb** [comment]
> https://operatorhub.io/operator/flux

The documentation is in `https://github.com/k8s-operatorhub/community-operators` and should be edited with the PR for the new version.

I have a concern with the way we do this though. I think most `openshift` users default to `OpenShift SDN`. So what we should do is take sometime to see if it is possible to add an `EgressNetworkPolicy` an test it.

**Comment by mestadler** [comment]
Ideally, I would ask that we provide the shortest path to having the update come out.  Do we have a way to test EgressNetworkPolicy simply, or does this need extensive effort to figure out.

**Comment by paulofrazao** [comment]
As part of the OperatorHub test script, it only tests that the pods start-up. 

This would take quite a bit of time and effort to validate/test.

**Comment by stefanprodan** [comment]
@paulofrazao it's easy to check if Flux is functional, create a source and Flux kustomization for podinfo then wait for it to reconcile., this e2e test will verify that the connection between controllers works when using network policies. 

Add the podinfo.yaml to the repo:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/manifests/podinfo
  ref:
    tag: "6.3.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: oci
  namespace: oci
spec:
  targetNamespace: default
  interval: 10m
  path: "./"
  prune: true
  sourceRef:
    kind: OCIRepository
    name: oci
  wait: true
  timeout: 2m
```

In CI apply and wait for podinfo to be reconciled:

```
kubectl apply -f podinfo.yaml
kubectl -n flux-system wait kustomization/podinfo --for=condition=ready --timeout=5m
kubectl -n default rollout status deploy/podinfo --timeout=1m
```

**Comment by souleb** [comment]
I tried testing this by installing it in a local openshift cluster... and it does not wprk.

I tried to package and when doing `operator-sdk bundle validate --select-optional name=operatorhub --verbose "flux/$version"`, I get the following error

```sh
ERRO[0000] Error: Value networking.k8s.io/v1, Kind=NetworkPolicy: unsupported media type registry+v1 for bundle object 
ERRO[0000] Error: Value networking.k8s.io/v1, Kind=NetworkPolicy: unsupported media type registry+v1 for bundle object 
ERRO[0000] Error: Value networking.k8s.io/v1, Kind=NetworkPolicy: unsupported media type registry+v1 for bundle object 
```
The validation seems required here and after some investigation it seems we already knew about this:
https://github.com/operator-framework/operator-lifecycle-manager/issues/1858

The current status is that `networkpolicies` will likely not be supported by `operator-sdk`, see https://github.com/operator-framework/operator-lifecycle-manager/issues/1996.

I also believe that Saada already addressed this by adding the following in the doc:
> Network Policies
> If you're using a CNI that requires network policies, you may need to [add Flux's policies]> (https://github.com/fluxcd/flux2/tree/main/manifests/policies).

I believe the only thing we can do, is to be more explicit in documenting that flux network policies have to be installed by the cluster admin.

**Comment by souleb** [comment]
So my conclusion is as follow:

I ran a test on  `openshift local` with a bundled flux v0.39.0.

```shell
⋊> ~ crc version                                                                                                                                                                       
CRC version: 2.13.1+b5b864fd
OpenShift version: 4.12.0
Podman version: 4.3.1
```

```shell
⋊> ~ oc get installplan -n flux-system                                                                                                                                                
NAME            CSV            APPROVAL    APPROVED
install-dgq5v   flux.v0.39.0   Automatic   true
```

```shell
⋊> ~ flux version                                                                                                                                                                      
flux: v0.39.0
helm-controller: v0.29.0
image-automation-controller: v0.29.0
image-reflector-controller: v0.24.0
kustomize-controller: v0.33.0
notification-controller: v0.31.0
source-controller: v0.34.0
```

I then manually applied the network policies

```shell
⋊> ~ oc get networkpolicies -n flux-system                                                                                                                                             
NAME             POD-SELECTOR                  AGE
allow-egress     <none>                        28m
allow-scraping   <none>                        28m
allow-webhooks   app=notification-controller   28m
```

And flux run as expected

```shell
⋊> ~ oc get kustomizations -n flux-system                                                                                                                                              
NAME   AGE   READY   STATUS
oci    21m   True    Applied revision: 6.3.0/fa482857dcbff9b405108ee1d773eaec053011a6f0a8023b2f492ff670aaa4c5

⋊> ~ oc get ocirepository -n flux-system                                                                                                                                               
NAME   URL                                            READY   STATUS                                                                                                AGE
oci    oci://ghcr.io/stefanprodan/manifests/podinfo   True    stored artifact for digest '6.3.0/fa482857dcbff9b405108ee1d773eaec053011a6f0a8023b2f492ff670aaa4c5'   26m
```

I have updated the PR accordingly, with a change of the description.

**Review by paulofrazao — APPROVED** [review]

**Comment by stefanprodan** [comment]
This name of this PR is misleading, please change it

**Pull request merged**
